version: "3.8"
services:
    db:
        image: mariadb:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravelpassword
        ports:
            - "3307:3306"
        volumes:
            - db_data:/var/lib/mysql
volumes:
    db_data:
